### ISSUE TITLE
Broken assembly reference compatibility between nuget packages

### ISSUE THREAD

**Issue by halex2005** [cake-contrib/Cake.CMake#12]
Is there any promise do not break compatibility? I have same issue for now: https://ci.appveyor.com/project/diadoc-admin/diadocsdk-cpp/build/job/2grisodnm1aj8gdu

```
Cake.CMake, Version=0.2.2.0 is referencing an older version of Cake.Core (0.18.0). 
This assembly need to reference at least Cake.Core version 0.22.0. 
```

My appveyor build is broken because of hard reference to specific version of Cake.
Why do we need this hard referencing?
What can we do to make this not happen again?
May be my PR #11 was not so bad?

There is another option about which Cake says:

```
It's not recommended, but you can explicitly opt-out of assembly verification 
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true", 
envrionment variable "CAKE_SETTINGS_SKIPVERIFICATION=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
```

I can use this setting, but I'd like to leave the verifications as is.

What is your thoughs?
What would you recommend?

**Comment by patriksvensson** [comment]
@halex2005 The recommendation is to pin both Cake and Cake.CMake to a working configuration. I will update Cake.CMake to build against Cake.Core 0.22.2, but you should always pin your dependencies to avoid broken builds.

**Comment by halex2005** [comment]
Assume I'm a new user, or I'm starting a new project from scratch with Cake.Cmake. I'll run to this exception because I'm haven't any working configuration yet. 

I'll have bad experience and could decide not to use cake at all.

We definitely need tool which will run without exceptions from scratch.
May be the solution is to update Cake.CMake package on every Cake release? Can we automate this?

**Comment by gep13** [comment]
The Cake 0.22.0 release was a major one. Lots of core fundamentals changed, for example, removing the Mono Compiler, and standardizing on Roslyn.

As a result, the decision was taken to ensure that addin authors had knowingly compiled their addin against this specific version.

This is not something which happens with every release of Cake.

**Comment by ubbeK** [comment]
I was hit by this issue today. Is there any chance that the `Cake.CMake` addin will be update to use the latest `Cake.Core` version anytime soon?

**Comment by patriksvensson** [comment]
@ubbeK Currently on vacation, but we accept PR:s.

**Comment by ubbeK** [comment]
@patriksvensson I see. 

Anywhere I can see some release notes for Cake? Especially the `0.22.0` one that @gep13 mentioned.

**Comment by patriksvensson** [comment]
@ubbeK If we update this addin, I would want us to update it to `0.25.0`. You can find release notes for each release at https://github.com/cake-build/cake/releases

**Comment by gep13** [comment]
@patriksvensson am I correct in saying that you meant `0.24.0` for Cake here?

**Comment by patriksvensson** [comment]
@gep13 Yes, of course. I meant `0.24.0`. Typo...

**Comment by darlov** [comment]
Is that actual issue because package was release with Cake.Core 0.34.1?
