### ISSUE TITLE
cmake is not resolved on Linux when in path

### ISSUE THREAD

**Issue by nathansoz** [cake-contrib/Cake.CMake#2]
When cmake is installed in the default path on linux it is not resolved. I believe this is because of https://github.com/patriksvensson/Cake.CMake/blob/master/src/Cake.CMake/CMakeRunner.cs#L71-L74 explicitly requesting cmake.exe. 

I'll test this, but I think you could either add "cmake" to the returned list or even just cut the .exe off to fix this issue. Once I verify this I'll submit a pull request and add a relevant unit test.

(As a workaround, you can symlink cmake to cmake.exe on linux and it is then resolved)

**Comment by patriksvensson** [comment]
@nathansoz Ah, never tested this on Linux to be honest. Adding `cmake` to the returned list as you suggested should solve the problem. A PR is more than welcome :smile:

**Comment by nathansoz** [comment]
Would it be possible to get the nuget package pushed for this? :)

**Comment by patriksvensson** [comment]
@nathansoz I've published the new package now (v0.1.0) but it might take a while for the package to properly index. Sorry for not doing this sooner. https://www.nuget.org/packages/Cake.CMake
