### ISSUE TITLE
Support "--config" when building

### ISSUE THREAD

**Issue by Breakpoint21** [cake-contrib/Cake.CMake#30]
CMake supports a "--config" flag for multi configuration tools (like Visual Studio)

(see: https://cmake.org/cmake/help/v3.15/manual/cmake.1.html#build-a-project)

I would be able to impement the feature myself.

**Comment by patriksvensson** [comment]
@Breakpoint21 Could you elaborate a bit what `--config` would do?

**Comment by Breakpoint21** [comment]
For instance i have a C++ project on windows which is build using cmake.
To install the binaries i call the "INSTALL" target - to be able to tell cmake which binaries (Debug or Release) i use the `--config` flag

**Comment by patriksvensson** [comment]
@Breakpoint21 Sorry, I thought this issue was posted in the Cake repository and was a bit confused. I'm tired today 😅. 

Sounds good to me! 👍
