### ISSUE TITLE
Passing options to native tool is not working (CMakeBuild)

### ISSUE THREAD

**Issue by Breakpoint21** [cake-contrib/Cake.CMake#31]
When adding Options to the `CMakeBuildSettings` they should be seperated from the other flags by `--`, acording to the cmake documentation (see: https://cmake.org/cmake/help/v3.15/manual/cmake.1.html#build-a-project)
Currently they are directly appended along with all other Settings

**Comment by darlov** [comment]
Thank you @Breakpoint21. The your fix has been released.
