### ISSUE TITLE
Switch away from using gep13.DefaultBuild and use Cake.Recipe instead

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.CMake#8]

**Comment by gep13** [comment]
@patriksvensson you want me to do this work?

If so, you happy for me to proceed with doing it?

**Comment by patriksvensson** [comment]
@gep13 This has been completed.

**Comment by gep13** [comment]
@patriksvensson hmm, I am not sure if everything is happening as it should.

The `.nuspec` file isn't in the expected folder, as a result, I don't think the NuGet package for the addin will be getting created.

**Comment by patriksvensson** [comment]
@gep13 Oh, where should it be?

**Comment by gep13** [comment]
By convention, it should be in a `nuspec\nuget` folder, from the root directory.  Otherwise, the nuget packaging step won't be completed.  You can also place nuspec files in `nuspec\chocolatey` and it will package them as chocolatey packages.

**Comment by gep13** [comment]
If you look here:

https://ci.appveyor.com/project/cakecontrib/cake-cmake/build/0.1.0-unstable.21.build.5#L411

You will see that the nuget packaging step has been skipped.  And also, no artifacts have been created:

https://ci.appveyor.com/project/cakecontrib/cake-cmake/build/0.1.0-unstable.21.build.5/artifacts

**Comment by patriksvensson** [comment]
@gep13 Ok, adding the nuspec seems to work. Do I have to do anything for the artifacts as well?

**Comment by patriksvensson** [comment]
@gep13 Seems to work now! Thanks! 😄

**Comment by gep13** [comment]
:+1:
